services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver2025
    hostname: sqlserver2025
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TestPassword123#"
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: true
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-volume:/var/opt/mssql
volumes:
  sqlserver-volume:
    external: true